#House price prediction

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.random.seed(42)

In [ ]:
area =np.random.randint(800,3001,10)

In [ ]:
print(area)

[1660 2094 1930 1895 2438 2969 1266 2038 1130 2282]

In [ ]:
bedroom = np.random.randint(1,6,10)

In [ ]:
bedroom

array([5, 4, 3, 5, 2, 4, 2, 4, 5, 1])

In [ ]:
age= np.random.randint(0,51,10)
age

array([11, 21, 43, 24, 48, 26, 41, 27, 15, 14])

In [ ]:
X = np.column_stack((area,bedroom,age))
X

array([[1660,    5,   11],
       [2094,    4,   21],
       [1930,    3,   43],
       [1895,    5,   24],
       [2438,    2,   48],
       [2969,    4,   26],
       [1266,    2,   41],
       [2038,    4,   27],
       [1130,    5,   15],
       [2282,    1,   14]])

In [ ]:
X.shape

(10, 3)

In [ ]:
area_price= area*3000

In [ ]:
area_price

array([4980000, 6282000, 5790000, 5685000, 7314000, 8907000, 3798000,
       6114000, 3390000, 6846000])

In [ ]:
bedroom_price =bedroom*200000
bedroom_price

array([1000000,  800000,  600000, 1000000,  400000,  800000,  400000,
        800000, 1000000,  200000])

In [ ]:
age_penalty=age*20000

In [ ]:
y =area_price+bedroom_price-age_penalty
y

array([5760000, 6662000, 5530000, 6205000, 6754000, 9187000, 3378000,
       6374000, 4090000, 6766000])

In [ ]:
y.shape

(10,)

In [ ]:
df =pd.DataFrame({
    "Area":area,
    "Bedroom":bedroom,
    "Age":age,
    "price":y
})
df

   Area  Bedroom  Age    price
0  1660        5   11  5760000
1  2094        4   21  6662000
2  1930        3   43  5530000
3  1895        5   24  6205000
4  2438        2   48  6754000
5  2969        4   26  9187000
6  1266        2   41  3378000
7  2038        4   27  6374000
8  1130        5   15  4090000
9  2282        1   14  6766000

In [ ]:
df.isnull().sum()

Area       0
Bedroom    0
Age        0
price      0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
print(model.coef_)
print(model.intercept_)

[  3000. 200000. -20000.]
-1.1175870895385742e-08

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([4090000., 6662000.])

In [ ]:
y_test

array([4090000, 6662000])

In [ ]:
from sklearn.metrics import mean_absolute_error
mae =mean_absolute_error(y_test,y_pred)

In [ ]:
mae

2.3283064365386963e-09

In [ ]:
print(np.allclose(y_pred,y_test))

True

In [ ]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,y_pred)

1.0842021724855044e-17

In [ ]:
rmse = np.sqrt(mse)
rmse

np.float64(3.2927225399135964e-09)